function writeParmParseInput(obj, path)
% Serialise the TimeTrack config to a ParmParse-format input file.
%
% Layout:
%   geom.lo, geom.hi, geom.ncell
%   beam.n_particles, beam.{x,y,z,ux,uy,uz}
%   lattice.elements = a b c
%   lattice.<name>.type = ...
%   lattice.<name>.<field> = ...
%   tracking.dt, tracking.n_steps
%   out_dir = ...

f = fopen(path, 'w');
if f < 0, error('writeParmParseInput:fopen', 'Cannot open %s', path); end
cleanup = onCleanup(@() fclose(f));

fprintf(f, '# Generated by TimeTrack on %s\n', datestr(now));

fprintf(f, '\n# ---- Geometry ----\n');
fprintf(f, 'geom.lo    = %.10g %.10g %.10g\n', obj.geom_lo);
fprintf(f, 'geom.hi    = %.10g %.10g %.10g\n', obj.geom_hi);
fprintf(f, 'geom.ncell = %d %d %d\n',          obj.geom_ncell);

fprintf(f, '\n# ---- Beam ----\n');
if isfield(obj.beam, 'seed_file') && ~isempty(obj.beam.seed_file)
    fprintf(f, 'beam.seed_file = %s\n', obj.beam.seed_file);
else
    fprintf(f, 'beam.n_particles = %d\n', obj.beam.n_particles);
    for fld = {'x','y','z','ux','uy','uz'}
        if isfield(obj.beam, fld{1})
            fprintf(f, 'beam.%s = %.10g\n', fld{1}, obj.beam.(fld{1}));
        end
    end
    if isfield(obj.beam, 'weight')
        fprintf(f, 'beam.weight = %.10g\n', obj.beam.weight);
    end
end

fprintf(f, '\n# ---- Lattice ----\n');
n_el = numel(obj.lattice);
names = cell(1, n_el);
for k = 1:n_el
    el = obj.lattice{k};
    if isfield(el, 'name') && ~isempty(el.name)
        names{k} = el.name;
    else
        names{k} = sprintf('el%d', k);
    end
end

fprintf(f, 'lattice.elements =');
for k = 1:n_el, fprintf(f, ' %s', names{k}); end
fprintf(f, '\n');

for k = 1:n_el
    el = obj.lattice{k};
    nm = names{k};
    fprintf(f, 'lattice.%s.type = %s\n', nm, el.type);
    flds = fieldnames(el);
    for j = 1:numel(flds)
        if any(strcmp(flds{j}, {'type', 'name'})), continue; end
        v = el.(flds{j});
        if isnumeric(v)
            if isscalar(v)
                if v == round(v) && abs(v) < 1e15
                    fprintf(f, 'lattice.%s.%s = %d\n', nm, flds{j}, v);
                else
                    fprintf(f, 'lattice.%s.%s = %.10g\n', nm, flds{j}, v);
                end
            else
                fprintf(f, 'lattice.%s.%s =', nm, flds{j});
                fprintf(f, ' %.10g', v(:).');
                fprintf(f, '\n');
            end
        elseif ischar(v) || isstring(v)
            fprintf(f, 'lattice.%s.%s = %s\n', nm, flds{j}, char(v));
        else
            warning('writeParmParseInput:skip', ...
                    'Skipping non-numeric/string field %s.%s', nm, flds{j});
        end
    end
end

fprintf(f, '\n# ---- Tracking ----\n');
fprintf(f, 'tracking.dt      = %.10g\n', obj.dt);
fprintf(f, 'tracking.n_steps = %d\n',    obj.n_steps);
if isprop(obj, 'dt_change_t') && ~isempty(obj.dt_change_t)
    fprintf(f, 'tracking.dt_change_t = %.10g\n', obj.dt_change_t);
end
if isprop(obj, 'dt_after') && ~isempty(obj.dt_after)
    fprintf(f, 'tracking.dt_after    = %.10g\n', obj.dt_after);
end

if obj.enable_space_charge
    fprintf(f, '\n# ---- Space charge ----\n');
    fprintf(f, 'space_charge.enabled = 1\n');
end

fprintf(f, '\nout_dir = %s\n', obj.output_dir);
end
