function writeParmParseInput(obj, path)
% Serialise the TimeTrack config to a ParmParse-format input file.
%
% Layout:
%   geom.lo, geom.hi, geom.ncell
%   beam.n_particles, beam.{x,y,z,ux,uy,uz}
%   lattice.elements = a b c
%   lattice.<name>.type = ...
%   lattice.<name>.<field> = ...
%   tracking.dt, tracking.n_steps
%   out_dir = ...

f = fopen(path, 'w');
if f < 0, error('writeParmParseInput:fopen', 'Cannot open %s', path); end
cleanup = onCleanup(@() fclose(f));

fprintf(f, '# Generated by TimeTrack on %s\n', datestr(now));

fprintf(f, '\n# ---- Geometry ----\n');
fprintf(f, 'geom.lo    = %.10g %.10g %.10g\n', obj.geom_lo);
fprintf(f, 'geom.hi    = %.10g %.10g %.10g\n', obj.geom_hi);
fprintf(f, 'geom.ncell = %d %d %d\n',          obj.geom_ncell);

fprintf(f, '\n# ---- Beam ----\n');
if isfield(obj.beam, 'partcl_file') && ~isempty(obj.beam.partcl_file)
    % ImpactT-style ASCII partcl.data seed (cross-code calibration).
    % Required: partcl_q_total (total |Q| in C). Optional: t_init.
    fprintf(f, 'beam.partcl_file    = %s\n', obj.beam.partcl_file);
    fprintf(f, 'beam.partcl_q_total = %.10g\n', obj.beam.partcl_q_total);
    if isfield(obj.beam, 't_init') && ~isempty(obj.beam.t_init)
        fprintf(f, 'beam.t_init         = %.10g\n', obj.beam.t_init);
    end
elseif isfield(obj.beam, 'seed_file') && ~isempty(obj.beam.seed_file)
    fprintf(f, 'beam.seed_file = %s\n', obj.beam.seed_file);
else
    fprintf(f, 'beam.n_particles = %d\n', obj.beam.n_particles);
    for fld = {'x','y','z','ux','uy','uz'}
        if isfield(obj.beam, fld{1})
            fprintf(f, 'beam.%s = %.10g\n', fld{1}, obj.beam.(fld{1}));
        end
    end
    if isfield(obj.beam, 'weight')
        fprintf(f, 'beam.weight = %.10g\n', obj.beam.weight);
    end
end

fprintf(f, '\n# ---- Lattice ----\n');
n_el = numel(obj.lattice);
names = cell(1, n_el);
for k = 1:n_el
    el = obj.lattice{k};
    if isfield(el, 'name') && ~isempty(el.name)
        names{k} = el.name;
    else
        names{k} = sprintf('el%d', k);
    end
end

fprintf(f, 'lattice.elements =');
for k = 1:n_el, fprintf(f, ' %s', names{k}); end
fprintf(f, '\n');

for k = 1:n_el
    el = obj.lattice{k};
    nm = names{k};
    fprintf(f, 'lattice.%s.type = %s\n', nm, el.type);
    flds = fieldnames(el);
    for j = 1:numel(flds)
        if any(strcmp(flds{j}, {'type', 'name'})), continue; end
        v = el.(flds{j});
        if isnumeric(v)
            if isscalar(v)
                if v == round(v) && abs(v) < 1e15
                    fprintf(f, 'lattice.%s.%s = %d\n', nm, flds{j}, v);
                else
                    fprintf(f, 'lattice.%s.%s = %.10g\n', nm, flds{j}, v);
                end
            else
                fprintf(f, 'lattice.%s.%s =', nm, flds{j});
                fprintf(f, ' %.10g', v(:).');
                fprintf(f, '\n');
            end
        elseif ischar(v) || isstring(v)
            fprintf(f, 'lattice.%s.%s = %s\n', nm, flds{j}, char(v));
        else
            warning('writeParmParseInput:skip', ...
                    'Skipping non-numeric/string field %s.%s', nm, flds{j});
        end
    end
end

fprintf(f, '\n# ---- Tracking ----\n');
fprintf(f, 'tracking.dt      = %.10g\n', obj.dt);
fprintf(f, 'tracking.n_steps = %d\n',    obj.n_steps);
if isprop(obj, 'dt_change_t') && ~isempty(obj.dt_change_t)
    fprintf(f, 'tracking.dt_change_t = %.10g\n', obj.dt_change_t);
end
if isprop(obj, 'dt_change_z') && ~isempty(obj.dt_change_z)
    fprintf(f, 'tracking.dt_change_z = %.10g\n', obj.dt_change_z);
end
if isprop(obj, 'dt_after') && ~isempty(obj.dt_after)
    fprintf(f, 'tracking.dt_after    = %.10g\n', obj.dt_after);
end
if isprop(obj, 't_start') && ~isempty(obj.t_start)
    fprintf(f, 'tracking.t_start     = %.10g\n', obj.t_start);
end
if isprop(obj, 'behind_cathode_z') && ~isempty(obj.behind_cathode_z) ...
        && isprop(obj, 'behind_cathode_betazini') && ~isempty(obj.behind_cathode_betazini)
    fprintf(f, 'tracking.behind_cathode_z        = %.10g\n', obj.behind_cathode_z);
    fprintf(f, 'tracking.behind_cathode_betazini = %.10g\n', obj.behind_cathode_betazini);
end
if isprop(obj, 'use_centroid_phase') && ~isempty(obj.use_centroid_phase) && obj.use_centroid_phase
    fprintf(f, 'tracking.use_centroid_phase = 1\n');
    if isprop(obj, 'centroid_t_offset') && ~isempty(obj.centroid_t_offset)
        fprintf(f, 'tracking.centroid_t_offset  = %.10g\n', obj.centroid_t_offset);
    end
end
if isprop(obj, 'use_midstep_field') && ~isempty(obj.use_midstep_field) && obj.use_midstep_field
    fprintf(f, 'tracking.use_midstep_field  = 1\n');
end
if isprop(obj, 'use_particle_phase') && ~isempty(obj.use_particle_phase) && obj.use_particle_phase
    fprintf(f, 'tracking.use_particle_phase = 1\n');
end
if isprop(obj, 'use_dkd_integrator') && ~isempty(obj.use_dkd_integrator)
    fprintf(f, 'tracking.use_dkd_integrator = %d\n', double(~~obj.use_dkd_integrator));
end
if isprop(obj, 'disable_self_force') && ~isempty(obj.disable_self_force) && obj.disable_self_force
    fprintf(f, 'tracking.disable_self_force = 1\n');
end
if isprop(obj, 'sc_use_b_field') && ~isempty(obj.sc_use_b_field) && obj.sc_use_b_field
    fprintf(f, 'tracking.sc_use_b_field = 1\n');
end
if isprop(obj, 'self_force_direct') && ~isempty(obj.self_force_direct) && obj.self_force_direct
    fprintf(f, 'tracking.self_force_direct = 1\n');
end
if isprop(obj, 'n_emission_steps') && ~isempty(obj.n_emission_steps) && obj.n_emission_steps > 0
    fprintf(f, 'tracking.n_emission_steps = %d\n', round(obj.n_emission_steps));
    fprintf(f, 'tracking.t_emission = %.10g\n', obj.t_emission);
    % dt_normal (phase 2) is the caller's dt_initial — write it here so main.cpp
    % can restore it after the emission phase ends (via the dt promotion).
    % We don't write it directly because main.cpp handles it internally.
end
if isprop(obj, 'particle_trace_ids') && ~isempty(obj.particle_trace_ids)
    ids = int32(obj.particle_trace_ids(:)');
    fprintf(f, 'tracking.particle_trace_ids =');
    fprintf(f, ' %d', ids);
    fprintf(f, '\n');
    interval = max(1, round(obj.particle_trace_interval));
    fprintf(f, 'tracking.particle_trace_interval = %d\n', interval);
    if isprop(obj, 'particle_trace_path') && ~isempty(obj.particle_trace_path)
        fprintf(f, 'tracking.particle_trace_path = %s\n', char(obj.particle_trace_path));
    end
end
if isprop(obj, 'dump_kicks_at_steps') && ~isempty(obj.dump_kicks_at_steps)
    steps = round(obj.dump_kicks_at_steps(:)');
    fprintf(f, 'tracking.dump_kicks_at_steps =');
    fprintf(f, ' %d', steps);
    fprintf(f, '\n');
end
if isprop(obj, 'dump_kicks_at_times') && ~isempty(obj.dump_kicks_at_times)
    times = obj.dump_kicks_at_times(:)';
    fprintf(f, 'tracking.dump_kicks_at_times =');
    fprintf(f, ' %.10g', times);
    fprintf(f, '\n');
end
if (isprop(obj, 'dump_kicks_at_steps') && ~isempty(obj.dump_kicks_at_steps)) ...
   || (isprop(obj, 'dump_kicks_at_times') && ~isempty(obj.dump_kicks_at_times))
    if isprop(obj, 'dump_kicks_path_prefix') && ~isempty(obj.dump_kicks_path_prefix)
        fprintf(f, 'tracking.dump_kicks_path_prefix = %s\n', char(obj.dump_kicks_path_prefix));
    end
end
if isprop(obj, 'trace_file') && ~isempty(obj.trace_file)
    fprintf(f, 'tracking.trace_file         = %s\n', char(obj.trace_file));
    if isprop(obj, 'trace_every') && ~isempty(obj.trace_every)
        fprintf(f, 'tracking.trace_every        = %d\n', round(obj.trace_every));
    end
end
if isprop(obj, 'field_audit_ids') && ~isempty(obj.field_audit_ids) ...
        && isprop(obj, 'field_audit_interval') && obj.field_audit_interval > 0
    ids = int32(obj.field_audit_ids(:)');
    fprintf(f, 'tracking.field_audit_ids =');
    fprintf(f, ' %d', ids);
    fprintf(f, '\n');
    fprintf(f, 'tracking.field_audit_interval = %d\n', round(obj.field_audit_interval));
    if isprop(obj, 'field_audit_file') && ~isempty(obj.field_audit_file)
        fprintf(f, 'tracking.field_audit_path = %s\n', char(obj.field_audit_file));
    end
end
if isprop(obj, 'sc_transverse_gamma_boost')
    fprintf(f, 'tracking.sc_transverse_gamma_boost = %d\n', round(obj.sc_transverse_gamma_boost));
end

if obj.enable_space_charge
    fprintf(f, '\n# ---- Space charge ----\n');
    fprintf(f, 'space_charge.enabled = 1\n');
    if isprop(obj, 'sc_comoving') && obj.sc_comoving
        fprintf(f, 'space_charge.comoving = 1\n');
    end
    if isprop(obj, 'sc_adaptive') && obj.sc_adaptive
        fprintf(f, 'space_charge.adaptive = 1\n');
        if isprop(obj, 'sc_pad_factor') && ~isempty(obj.sc_pad_factor)
            fprintf(f, 'space_charge.pad_factor = %.6g\n', obj.sc_pad_factor);
        end
        if isprop(obj, 'sc_resize_hyst') && ~isempty(obj.sc_resize_hyst) && obj.sc_resize_hyst ~= 2.0
            fprintf(f, 'space_charge.resize_hyst = %.6g\n', obj.sc_resize_hyst);
        end
        if isprop(obj, 'sc_cent_drift_threshold') && ~isempty(obj.sc_cent_drift_threshold) && obj.sc_cent_drift_threshold ~= 0.5
            fprintf(f, 'space_charge.cent_drift_threshold = %.6g\n', obj.sc_cent_drift_threshold);
        end
        if isprop(obj, 'sc_integer_cell_shift') && ~isempty(obj.sc_integer_cell_shift) && obj.sc_integer_cell_shift
            fprintf(f, 'space_charge.integer_cell_shift = 1\n');
        end
        if isprop(obj, 'sc_min_pad_xy') && ~isempty(obj.sc_min_pad_xy)
            fprintf(f, 'space_charge.min_pad_xy = %.6g\n', obj.sc_min_pad_xy);
        end
        if isprop(obj, 'sc_min_pad_z') && ~isempty(obj.sc_min_pad_z)
            fprintf(f, 'space_charge.min_pad_z = %.6g\n', obj.sc_min_pad_z);
        end
    end
    if isprop(obj, 'sc_exact_range') && obj.sc_exact_range
        fprintf(f, 'space_charge.exact_range = 1\n');
    end
    if isprop(obj, 'sc_outlier_kill_sigma') && ~isempty(obj.sc_outlier_kill_sigma) && obj.sc_outlier_kill_sigma > 0
        fprintf(f, 'space_charge.outlier_kill_sigma = %.6g\n', obj.sc_outlier_kill_sigma);
        if isprop(obj, 'sc_outlier_kill_floor_xy') && ~isempty(obj.sc_outlier_kill_floor_xy) && obj.sc_outlier_kill_floor_xy > 0
            fprintf(f, 'space_charge.outlier_kill_floor_xy = %.6g\n', obj.sc_outlier_kill_floor_xy);
        end
        if isprop(obj, 'sc_outlier_kill_floor_z') && ~isempty(obj.sc_outlier_kill_floor_z) && obj.sc_outlier_kill_floor_z > 0
            fprintf(f, 'space_charge.outlier_kill_floor_z = %.6g\n', obj.sc_outlier_kill_floor_z);
        end
        if isprop(obj, 'sc_outlier_kill_verbose') && obj.sc_outlier_kill_verbose
            fprintf(f, 'space_charge.outlier_kill_verbose = 1\n');
        end
    end
    if isprop(obj, 'sc_hybrid_z_adaptive') && obj.sc_hybrid_z_adaptive
        fprintf(f, 'space_charge.hybrid_z_adaptive = 1\n');
    end
    if isprop(obj, 'sc_image_plane') && obj.sc_image_plane
        fprintf(f, 'space_charge.image_plane_enabled = 1\n');
        fprintf(f, 'space_charge.image_plane_z = %.10g\n', obj.sc_image_plane_z);
        fprintf(f, 'space_charge.image_cutoff = %.10g\n', obj.sc_image_cutoff);
    end
    if isprop(obj, 'sc_rho_smooth_passes') && ~isempty(obj.sc_rho_smooth_passes) && obj.sc_rho_smooth_passes > 0
        fprintf(f, 'space_charge.rho_smooth_passes = %d\n', round(obj.sc_rho_smooth_passes));
    end
    if isprop(obj, 'sc_green_cache_tol') && ~isempty(obj.sc_green_cache_tol) && obj.sc_green_cache_tol > 0
        fprintf(f, 'space_charge.green_cache_tol = %.10g\n', obj.sc_green_cache_tol);
    end
    if isprop(obj, 'sc_shape_order') && ~isempty(obj.sc_shape_order) && obj.sc_shape_order ~= 1
        fprintf(f, 'space_charge.shape_order = %d\n', round(obj.sc_shape_order));
    end
    if isprop(obj, 'sc_verbose') && ~isempty(obj.sc_verbose) && obj.sc_verbose > 0
        fprintf(f, 'space_charge.verbose = %d\n', round(obj.sc_verbose));
    end
    if isprop(obj, 'sc_diag_resize_jump') && ~isempty(obj.sc_diag_resize_jump) && obj.sc_diag_resize_jump > 0
        fprintf(f, 'space_charge.diag_resize_jump = %d\n', round(obj.sc_diag_resize_jump));
    end
    if isprop(obj, 'sc_dump_field_at_step') && ~isempty(obj.sc_dump_field_at_step) && obj.sc_dump_field_at_step > 0
        fprintf(f, 'space_charge.dump_field_at_step = %d\n', round(obj.sc_dump_field_at_step));
        if isprop(obj, 'sc_dump_field_path') && ~isempty(obj.sc_dump_field_path)
            fprintf(f, 'space_charge.dump_field_path = %s\n', obj.sc_dump_field_path);
        end
    end
end
if isprop(obj, 'enable_slice_sc') && obj.enable_slice_sc
    if ~obj.enable_space_charge
        fprintf(f, '\n# ---- Space charge (slice only) ----\n');
    end
    fprintf(f, 'space_charge.slice_enabled = 1\n');
    if isprop(obj, 'slice_sc_n') && ~isempty(obj.slice_sc_n)
        fprintf(f, 'space_charge.slice_n = %d\n', round(obj.slice_sc_n));
    end
    if isprop(obj, 'slice_sc_radius_factor') && ~isempty(obj.slice_sc_radius_factor)
        fprintf(f, 'space_charge.slice_radius_factor = %.6g\n', obj.slice_sc_radius_factor);
    end
    if isprop(obj, 'slice_sc_profile') && ~isempty(obj.slice_sc_profile) && obj.slice_sc_profile ~= 0
        fprintf(f, 'space_charge.slice_profile = %d\n', round(obj.slice_sc_profile));
    end
    if isprop(obj, 'slice_sc_gamma_off') && ~isempty(obj.slice_sc_gamma_off)
        fprintf(f, 'space_charge.slice_gamma_off = %.6g\n', obj.slice_sc_gamma_off);
    end
end

fprintf(f, '\nout_dir = %s\n', obj.output_dir);
end
