function writeParmParseInput(obj, path)
% Serialise the TimeTrack config to a ParmParse-format input file.
%
% Layout:
%   geom.lo, geom.hi, geom.ncell
%   beam.n_particles, beam.{x,y,z,ux,uy,uz}
%   lattice.elements = a b c
%   lattice.<name>.type = ...
%   lattice.<name>.<field> = ...
%   tracking.dt, tracking.n_steps
%   out_dir = ...

f = fopen(path, 'w');
if f < 0, error('writeParmParseInput:fopen', 'Cannot open %s', path); end
cleanup = onCleanup(@() fclose(f));

fprintf(f, '# Generated by TimeTrack on %s\n', datestr(now));

fprintf(f, '\n# ---- Geometry ----\n');
fprintf(f, 'geom.lo    = %.10g %.10g %.10g\n', obj.geom_lo);
fprintf(f, 'geom.hi    = %.10g %.10g %.10g\n', obj.geom_hi);
fprintf(f, 'geom.ncell = %d %d %d\n',          obj.geom_ncell);

fprintf(f, '\n# ---- Beam ----\n');
if isfield(obj.beam, 'partcl_file') && ~isempty(obj.beam.partcl_file)
    % ImpactT-style ASCII partcl.data seed (cross-code calibration).
    % Required: partcl_q_total (total |Q| in C). Optional: t_init.
    fprintf(f, 'beam.partcl_file    = %s\n', obj.beam.partcl_file);
    fprintf(f, 'beam.partcl_q_total = %.10g\n', obj.beam.partcl_q_total);
    if isfield(obj.beam, 't_init') && ~isempty(obj.beam.t_init)
        fprintf(f, 'beam.t_init         = %.10g\n', obj.beam.t_init);
    end
elseif isfield(obj.beam, 'seed_file') && ~isempty(obj.beam.seed_file)
    fprintf(f, 'beam.seed_file = %s\n', obj.beam.seed_file);
else
    fprintf(f, 'beam.n_particles = %d\n', obj.beam.n_particles);
    for fld = {'x','y','z','ux','uy','uz'}
        if isfield(obj.beam, fld{1})
            fprintf(f, 'beam.%s = %.10g\n', fld{1}, obj.beam.(fld{1}));
        end
    end
    if isfield(obj.beam, 'weight')
        fprintf(f, 'beam.weight = %.10g\n', obj.beam.weight);
    end
end

fprintf(f, '\n# ---- Lattice ----\n');
n_el = numel(obj.lattice);
names = cell(1, n_el);
for k = 1:n_el
    el = obj.lattice{k};
    if isfield(el, 'name') && ~isempty(el.name)
        names{k} = el.name;
    else
        names{k} = sprintf('el%d', k);
    end
end

fprintf(f, 'lattice.elements =');
for k = 1:n_el, fprintf(f, ' %s', names{k}); end
fprintf(f, '\n');

for k = 1:n_el
    el = obj.lattice{k};
    nm = names{k};
    fprintf(f, 'lattice.%s.type = %s\n', nm, el.type);
    flds = fieldnames(el);
    for j = 1:numel(flds)
        if any(strcmp(flds{j}, {'type', 'name'})), continue; end
        v = el.(flds{j});
        if isnumeric(v)
            if isscalar(v)
                if v == round(v) && abs(v) < 1e15
                    fprintf(f, 'lattice.%s.%s = %d\n', nm, flds{j}, v);
                else
                    fprintf(f, 'lattice.%s.%s = %.10g\n', nm, flds{j}, v);
                end
            else
                fprintf(f, 'lattice.%s.%s =', nm, flds{j});
                fprintf(f, ' %.10g', v(:).');
                fprintf(f, '\n');
            end
        elseif ischar(v) || isstring(v)
            fprintf(f, 'lattice.%s.%s = %s\n', nm, flds{j}, char(v));
        else
            warning('writeParmParseInput:skip', ...
                    'Skipping non-numeric/string field %s.%s', nm, flds{j});
        end
    end
end

fprintf(f, '\n# ---- Tracking ----\n');
fprintf(f, 'tracking.dt      = %.10g\n', obj.dt);
fprintf(f, 'tracking.n_steps = %d\n',    obj.n_steps);
if isprop(obj, 'dt_change_t') && ~isempty(obj.dt_change_t)
    fprintf(f, 'tracking.dt_change_t = %.10g\n', obj.dt_change_t);
end
if isprop(obj, 'dt_change_z') && ~isempty(obj.dt_change_z)
    fprintf(f, 'tracking.dt_change_z = %.10g\n', obj.dt_change_z);
end
if isprop(obj, 'dt_after') && ~isempty(obj.dt_after)
    fprintf(f, 'tracking.dt_after    = %.10g\n', obj.dt_after);
end
if isprop(obj, 't_start') && ~isempty(obj.t_start)
    fprintf(f, 'tracking.t_start     = %.10g\n', obj.t_start);
end
if isprop(obj, 'behind_cathode_z') && ~isempty(obj.behind_cathode_z) ...
        && isprop(obj, 'behind_cathode_betazini') && ~isempty(obj.behind_cathode_betazini)
    fprintf(f, 'tracking.behind_cathode_z        = %.10g\n', obj.behind_cathode_z);
    fprintf(f, 'tracking.behind_cathode_betazini = %.10g\n', obj.behind_cathode_betazini);
end
if isprop(obj, 'use_centroid_phase') && ~isempty(obj.use_centroid_phase) && obj.use_centroid_phase
    fprintf(f, 'tracking.use_centroid_phase = 1\n');
    if isprop(obj, 'centroid_t_offset') && ~isempty(obj.centroid_t_offset)
        fprintf(f, 'tracking.centroid_t_offset  = %.10g\n', obj.centroid_t_offset);
    end
end
if isprop(obj, 'use_midstep_field') && ~isempty(obj.use_midstep_field) && obj.use_midstep_field
    fprintf(f, 'tracking.use_midstep_field  = 1\n');
end
if isprop(obj, 'use_particle_phase') && ~isempty(obj.use_particle_phase) && obj.use_particle_phase
    fprintf(f, 'tracking.use_particle_phase = 1\n');
end
if isprop(obj, 'use_dkd_integrator') && ~isempty(obj.use_dkd_integrator) && obj.use_dkd_integrator
    fprintf(f, 'tracking.use_dkd_integrator = 1\n');
end
if isprop(obj, 'disable_self_force') && ~isempty(obj.disable_self_force) && obj.disable_self_force
    fprintf(f, 'tracking.disable_self_force = 1\n');
end
if isprop(obj, 'sc_use_b_field') && ~isempty(obj.sc_use_b_field) && obj.sc_use_b_field
    fprintf(f, 'tracking.sc_use_b_field = 1\n');
end
if isprop(obj, 'trace_file') && ~isempty(obj.trace_file)
    fprintf(f, 'tracking.trace_file         = %s\n', char(obj.trace_file));
    if isprop(obj, 'trace_every') && ~isempty(obj.trace_every)
        fprintf(f, 'tracking.trace_every        = %d\n', round(obj.trace_every));
    end
end

if obj.enable_space_charge
    fprintf(f, '\n# ---- Space charge ----\n');
    fprintf(f, 'space_charge.enabled = 1\n');
    if isprop(obj, 'sc_comoving') && obj.sc_comoving
        fprintf(f, 'space_charge.comoving = 1\n');
    end
    if isprop(obj, 'sc_adaptive') && obj.sc_adaptive
        fprintf(f, 'space_charge.adaptive = 1\n');
        if isprop(obj, 'sc_pad_factor') && ~isempty(obj.sc_pad_factor)
            fprintf(f, 'space_charge.pad_factor = %.6g\n', obj.sc_pad_factor);
        end
        if isprop(obj, 'sc_min_pad_xy') && ~isempty(obj.sc_min_pad_xy)
            fprintf(f, 'space_charge.min_pad_xy = %.6g\n', obj.sc_min_pad_xy);
        end
        if isprop(obj, 'sc_min_pad_z') && ~isempty(obj.sc_min_pad_z)
            fprintf(f, 'space_charge.min_pad_z = %.6g\n', obj.sc_min_pad_z);
        end
    end
    if isprop(obj, 'sc_exact_range') && obj.sc_exact_range
        fprintf(f, 'space_charge.exact_range = 1\n');
    end
    if isprop(obj, 'sc_hybrid_z_adaptive') && obj.sc_hybrid_z_adaptive
        fprintf(f, 'space_charge.hybrid_z_adaptive = 1\n');
    end
    if isprop(obj, 'sc_image_plane') && obj.sc_image_plane
        fprintf(f, 'space_charge.image_plane_enabled = 1\n');
        fprintf(f, 'space_charge.image_plane_z = %.10g\n', obj.sc_image_plane_z);
        fprintf(f, 'space_charge.image_cutoff = %.10g\n', obj.sc_image_cutoff);
    end
    if isprop(obj, 'sc_rho_smooth_passes') && ~isempty(obj.sc_rho_smooth_passes) && obj.sc_rho_smooth_passes > 0
        fprintf(f, 'space_charge.rho_smooth_passes = %d\n', round(obj.sc_rho_smooth_passes));
    end
    if isprop(obj, 'sc_shape_order') && ~isempty(obj.sc_shape_order) && obj.sc_shape_order ~= 1
        fprintf(f, 'space_charge.shape_order = %d\n', round(obj.sc_shape_order));
    end
    if isprop(obj, 'sc_verbose') && ~isempty(obj.sc_verbose) && obj.sc_verbose > 0
        fprintf(f, 'space_charge.verbose = %d\n', round(obj.sc_verbose));
    end
end
if isprop(obj, 'enable_slice_sc') && obj.enable_slice_sc
    if ~obj.enable_space_charge
        fprintf(f, '\n# ---- Space charge (slice only) ----\n');
    end
    fprintf(f, 'space_charge.slice_enabled = 1\n');
    if isprop(obj, 'slice_sc_n') && ~isempty(obj.slice_sc_n)
        fprintf(f, 'space_charge.slice_n = %d\n', round(obj.slice_sc_n));
    end
    if isprop(obj, 'slice_sc_radius_factor') && ~isempty(obj.slice_sc_radius_factor)
        fprintf(f, 'space_charge.slice_radius_factor = %.6g\n', obj.slice_sc_radius_factor);
    end
    if isprop(obj, 'slice_sc_gamma_off') && ~isempty(obj.slice_sc_gamma_off)
        fprintf(f, 'space_charge.slice_gamma_off = %.6g\n', obj.slice_sc_gamma_off);
    end
end

fprintf(f, '\nout_dir = %s\n', obj.output_dir);
end
