function s = CathodeSource(varargin)
% CATHODESOURCE  Spec a cathode emission source + image-charge plane.
%
% s = timetracking.CathodeSource('z_cathode', 0, ...
%                                 'n_macroparticles_total', 1000, ...
%                                 'total_charge', 1e-9, ...
%                                 'pulse_shape', 'gaussian', ...
%                                 'pulse_duration', 10e-12, ...
%                                 'pulse_t0', 30e-12, ...
%                                 'transverse_profile', 'gaussian', ...
%                                 'spot_size', 0.5e-3, ...
%                                 'mte', 0.5)
%
% Use 'image_charge', false to disable the self-image E_z contribution.
% Use 'n_macroparticles_total', 0 to disable emission entirely.
%
% Pulse shape options: 'gaussian' (FWHM = pulse_duration), 'flat_top'.
% Transverse profile options: 'gaussian' (RMS = spot_size), 'uniform_disk'.
% mte (mean transverse energy) is in eV.

p = inputParser;
p.addParameter('name',                   'CAT',  @(x) ischar(x) || isstring(x));
p.addParameter('z_cathode',              0.0,    @isnumeric);
p.addParameter('image_charge',           true,   @(x) islogical(x) || isnumeric(x));
p.addParameter('n_macroparticles_total', 0,      @(x) isnumeric(x) && isscalar(x));
p.addParameter('total_charge',           0.0,    @isnumeric);
p.addParameter('pulse_shape',            'gaussian', @(x) any(strcmp(x, {'gaussian','flat_top'})));
p.addParameter('pulse_duration',         0.0,    @isnumeric);
p.addParameter('pulse_t0',               0.0,    @isnumeric);
p.addParameter('transverse_profile',     'gaussian', @(x) any(strcmp(x, {'gaussian','uniform_disk'})));
p.addParameter('spot_size',              0.0,    @isnumeric);
p.addParameter('mte',                    0.0,    @isnumeric);
p.parse(varargin{:});
r = p.Results;

s = struct('type',                   'cathode_source', ...
           'name',                   char(r.name), ...
           'z_cathode',              r.z_cathode, ...
           'image_charge',           double(logical(r.image_charge)), ...
           'n_macroparticles_total', r.n_macroparticles_total, ...
           'total_charge',           r.total_charge, ...
           'pulse_shape',            char(r.pulse_shape), ...
           'pulse_duration',         r.pulse_duration, ...
           'pulse_t0',               r.pulse_t0, ...
           'transverse_profile',     char(r.transverse_profile), ...
           'spot_size',              r.spot_size, ...
           'mte',                    r.mte);
end
