function s = CathodeSource(varargin)
% CATHODESOURCE  Spec a cathode emission source + image-charge plane.
%
% s = timetracking.CathodeSource('z_cathode', 0, ...
%                                 'n_macroparticles_total', 1000, ...
%                                 'total_charge', 1e-9, ...
%                                 'pulse_shape', 'gaussian', ...
%                                 'pulse_duration', 10e-12, ...
%                                 'pulse_t0', 30e-12, ...
%                                 'transverse_profile', 'gaussian', ...
%                                 'spot_size', 0.5e-3, ...
%                                 'mte', 0.5)
%
% Use 'image_charge', false to disable the self-image E_z contribution.
% Use 'n_macroparticles_total', 0 to disable emission entirely.
%
% Pulse shape options:
%   'gaussian'        FWHM = pulse_duration (RMS = pulse_duration / 2.355)
%   'flat_top'        full width = pulse_duration
%   'super_gaussian'  pulse_duration is sigma (NOT FWHM); pulse_alpha sets
%                     the shape (alpha=1 -> Gaussian, alpha=0.5 mild flat-
%                     top, alpha->0 uniform-with-edges); pulse_slope adds
%                     a deformable linear ramp matching distgen
% Transverse profile options:
%   'gaussian'        RMS = spot_size (each transverse component)
%   'uniform_disk'    radius = spot_size, uniform on the disk
%   'super_gaussian'  spot_size is sigma; transverse_alpha sets the shape;
%                     transverse_truncate (units of sigma; 0 -> 4*sigma)
%                     bounds the radial support
% mte (mean transverse energy) is in eV.

p = inputParser;
p.addParameter('name',                   'CAT',  @(x) ischar(x) || isstring(x));
p.addParameter('z_cathode',              0.0,    @isnumeric);
p.addParameter('image_charge',           true,   @(x) islogical(x) || isnumeric(x));
p.addParameter('n_macroparticles_total', 0,      @(x) isnumeric(x) && isscalar(x));
p.addParameter('total_charge',           0.0,    @isnumeric);
p.addParameter('pulse_shape',            'gaussian', @(x) any(strcmp(x, {'gaussian','flat_top','super_gaussian'})));
p.addParameter('pulse_duration',         0.0,    @isnumeric);
p.addParameter('pulse_t0',               0.0,    @isnumeric);
p.addParameter('transverse_profile',     'gaussian', @(x) any(strcmp(x, {'gaussian','uniform_disk','super_gaussian'})));
p.addParameter('spot_size',              0.0,    @isnumeric);
p.addParameter('mte',                    0.0,    @isnumeric);
% SuperGaussian-only params (ignored unless the corresponding shape is
% 'super_gaussian').
p.addParameter('pulse_alpha',            1.0,    @isnumeric);
p.addParameter('pulse_slope',            0.0,    @isnumeric);
p.addParameter('transverse_alpha',       1.0,    @isnumeric);
p.addParameter('transverse_truncate',    0.0,    @isnumeric);
% ImpactT-style emission options (off by default).
%   longitudinal_thermal: sample uz from half-Maxwell |Normal(0, sigma_u)|
%       with sigma_u = sqrt(MTE * |e| / m_e). Matches distgen-generated
%       partcl.data when the same MTE is used in both codes.
%   z_init_spread: initial z is uniform in [z_cathode - spread, z_cathode].
%       Combined with TimeTrack.behind_cathode_betazini (>0), particles
%       drift at the universal speed until z >= z_cathode, mirroring
%       ImpactT's driftemission_BeamBunch.
p.addParameter('longitudinal_thermal',   false,  @(x) islogical(x) || isnumeric(x));
p.addParameter('z_init_spread',          0.0,    @isnumeric);
p.parse(varargin{:});
r = p.Results;

s = struct('type',                   'cathode_source', ...
           'name',                   char(r.name), ...
           'z_cathode',              r.z_cathode, ...
           'image_charge',           double(logical(r.image_charge)), ...
           'n_macroparticles_total', r.n_macroparticles_total, ...
           'total_charge',           r.total_charge, ...
           'pulse_shape',            char(r.pulse_shape), ...
           'pulse_duration',         r.pulse_duration, ...
           'pulse_t0',               r.pulse_t0, ...
           'transverse_profile',     char(r.transverse_profile), ...
           'spot_size',              r.spot_size, ...
           'mte',                    r.mte, ...
           'pulse_alpha',            r.pulse_alpha, ...
           'pulse_slope',            r.pulse_slope, ...
           'transverse_alpha',       r.transverse_alpha, ...
           'transverse_truncate',    r.transverse_truncate, ...
           'longitudinal_thermal',   double(logical(r.longitudinal_thermal)), ...
           'z_init_spread',          r.z_init_spread);
end
